import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import type { Metadata } from 'next';
import './globals.css';

const gillSans = localFont({
  src: [
    {
      path: './fonts/gillSans/GillSans-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/gillSans/GillSans-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/gillSans/GillSans-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/gillSans/GillSans-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${gillSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
